name: "âœğŸ¼ Rename commit messages"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  opencommit:
    runs-on: ubuntu-latest
    name: âœğŸ¼ Rename commit messages
    permissions: write-all
    timeout-minutes: 5
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: âœğŸ¼ Rename commit messages
        uses: di-sukharev/opencommit@github-action-v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          OCO_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OCO_TOKENS_MAX_TOKENS: 500
          OCO_DESCRIPTION: true
          OCO_EMOJI: true
          OCO_MODEL: gpt-3.5-turbo
          OCO_LANGUAGE: en
