name: Code Quality Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sonarqube:
    name: ğŸ” SonarQube Quality Gate
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    steps:
      - name: ğŸ—ï¸ Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Triggering SonarQube analysis as results of it are required by Quality Gate check.
      - name: ğŸ” SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master

      # Check the Quality Gate status.
      - name: ğŸ“‹ SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5

  # gpt-review:
  #   name: ğŸ“‹ Chat GPT code review
  #   runs-on: ubuntu-latest
  #   needs: sonarqube
  #   steps:
  #     - name: ğŸ—ï¸ Setup repo
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: ğŸ“‹ Perform Chat GPT code review
  #       uses: mattzcarey/code-review-gpt@v0.1.4-alpha
  #       with:
  #         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  #         MODEL: 'gpt-3.5-turbo'
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}