name: ğŸ” Code Quality Check

on:
  pull_request:

jobs:
  sonarqube:
    name: ğŸ” SonarQube Quality Check
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    steps:
      - name: ğŸ—ï¸ Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Triggering SonarQube analysis as results of it are required by Quality Gate check.
      - name: ğŸ” SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master

      # Check the Quality Gate status.
      - name: ğŸ“‹ SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
